[build]
	command = "npm run build"
	publish = "build"

# Cache Images
[[headers]]
	for = "/photos/*"
	[headers.values]
		Cache-Control = "public, max-age=2629800, immutable"

# Cache Fonts
[[headers]]
	for = "/fonts/*"
	[headers.values]
		Cache-Control = "public, max-age=2629800, immutable"